### ISSUE TITLE
Obj files

### ISSUE THREAD

**Issue by francisdb** [luisbedoia/sx3d#1]
Would it be hard to add support for obj files?

**Comment by luisbedoia** [comment]
Thank you very much for your suggestion. I faced a difficulty because my project was tightly coupled to the data structures of the initial library (stl_io). To resolve this, I developed custom data structures (entities) for the project and wrote two translators: STL and OBJ. This turned out to be a better architectural approach, as it simplifies the addition of new formats to merely creating a new translator. 

The new code is already in the main branch; please test it. I look forward to any new suggestions.

**Comment by francisdb** [comment]
Thanks, tried it but got some error:

```
> RUST_BACKTRACE=1 sx3d Primitive.screw024.obj
...
               .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
               .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .




col: -6
       row: 13
              thread 'main' panicked at src/canvas/squared_canvas.rs:88:13:
                                                                           index out of bounds
                                                                                              stack backtrace:
                                                                                                                 0: _rust_begin_unwind
       1: core::panicking::panic_fmt
                                       2: sx3d::input_output::controller::Controller::get_frame
                                                                                                  3: sx3d::input_output::console::Console::start
                 4: sx3d::main
                              note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

[Primitive.screw024.obj.zip](https://github.com/user-attachments/files/17486605/Primitive.screw024.obj.zip)
